export const puzzleList = [
    'Naske',
    //'1905',
    'agu_unue',
    'ĉiu_timas_ion',
    'el_popola',
    'hans-paulige',
    'kun_spicoj',
    'la_zamenhofa_dimensio',
    'lauxdu_la_tagon',
    'mala_tago',
    'ne_de_jaroj',
    'nova_pli_vigla',
    'okazas',
    'po_tri_foje_jare',
    'revolucie',
    'senteme',
    'serpente',
    'skota_skadrono',
    'survoje',
    'sxi_kaj_mi',
    'unue',
    'Volume',
];
export const puzzleStore = {};